Repository ConsenSys/mythril, pull requests merged in 2018-08, with the labels that each got.

#391 Bugfix/fix fallback name
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/transaction.py
Labels: Review

#379 Codecopy implementation
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  tests/instructions/__init__.py
  tests/instructions/codecopy_test.py
  tests/report_test.py
Labels: Review

#396 Disable function name lookup in contract search, clean up commandline arguments
  mythril/disassembler/disassembly.py
  mythril/ether/ethcontract.py
  mythril/exceptions.py
  mythril/interfaces/cli.py
  mythril/leveldb/accountindexing.py
  mythril/leveldb/client.py
  mythril/support/loader.py
  mythril/support/signatures.py
Labels: Review

#386 Add truffle signatures
  mythril/mythril.py
  mythril/support/signatures.py
  mythril/support/truffle.py
Labels: Review

#408 Remove use of ipc variable
  mythril/interfaces/cli.py
Labels: Review

#412 Exclude invalid addresses from search results
  mythril/leveldb/client.py
Labels: Review

#414 Correct output when "-V -o json" option is given...
  mythril/interfaces/cli.py
  tests/test_cli_opts.py
Labels: in progress

#415 Fix codecopy for edge cases
  mythril/laser/ethereum/instructions.py
  mythril/leveldb/client.py
Labels: Review

#410 Adds title to callgraph.html
  mythril/analysis/templates/callgraph.html
Labels: Review

#416 List 'markdown' option in command line help
  mythril/interfaces/cli.py
Labels: Review

#404 Transaction based message calling
  mythril/interfaces/cli.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction.py
  mythril/mythril.py
  tests/laser/__init__.py
  tests/laser/test_transaction.py
Labels: Review

#421 add maintainability
  README.md
Labels: in progress

#419 Contract creation transaction
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction.py
  tests/laser/state/__init__.py
  tests/laser/state/mstate_test.py
  tests/laser/transaction/__init__.py
  tests/laser/transaction/create.py
Labels: Review

#420 Perform check based on transaction_stack
  mythril/laser/ethereum/taint_analysis.py
Labels: Review

#430 Add better lock support using sys calls
  mythril/support/signatures.py
Labels: Review

#434 Jumpi bugfix
  mythril/laser/ethereum/instructions.py
Labels: in progress

#433 Implements concretized storage
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction.py
Labels: Review

#431 Implements code based coveraged and initial reporting
  mythril/laser/ethereum/svm.py
Labels: in progress

#441 Fix integration tests
  mythril/support/signatures.py
Labels: Review

#438 Machine State dynamic pop implementation
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/state.py
  tests/laser/state/mstate_test.py
Labels: Review

#437 Do multiple transactions
  mythril/laser/ethereum/svm.py
Labels: Review

#439 Implement storage tests
  tests/laser/state/storage_test.py
Labels: Review

#443 Laser testing
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/modules/__init__.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction/__init__.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  tests/analysis/test_delegatecall.py
  tests/laser/test_transaction.py
  tests/laser/transaction/create_transaction_test.py
  tests/laser/transaction/symbolic_test.py
  tests/native_test.py
  tests/svm_test.py
  tests/taint_result_test.py
  tests/taint_runner_test.py
Labels: Review

#444 Fix merge issues
  mythril/laser/ethereum/svm.py
Labels: Review

#445 Enhance/436
  mythril/analysis/symbolic.py
  mythril/interfaces/cli.py
  mythril/laser/ethereum/svm.py
  mythril/mythril.py
  mythril/support/truffle.py
Labels: Review

#451 Filter on jumptype Transaction
  mythril/laser/ethereum/taint_analysis.py
Labels: in progress

#461 Add discord tag
  README.md
Labels: Review

#462 Merge OS and OS-version fields
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Review

#455 remove ipc module
  mythril/interfaces/cli.py
  mythril/ipc/__init__.py
  mythril/ipc/client.py
  mythril/ipc/constants.py
  mythril/ipc/exceptions.py
  mythril/ipc/utils.py
  mythril/mythril.py
  tests/ipc_test.py
Labels: Review

#465 Concolic exec and tests
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction/concolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  tests/laser/evm_testsuite/VMTests/LICENSE
  tests/laser/evm_testsuite/VMTests/README.md
  tests/laser/evm_testsuite/VMTests/vmArithmeticTest/add0.json
  tests/laser/evm_testsuite/VMTests/vmArithmeticTest/add1.json
  tests/laser/evm_testsuite/VMTests/vmArithmeticTest/add2.json
  tests/laser/evm_testsuite/VMTests/vmArithmeticTest/add3.json
  tests/laser/evm_testsuite/VMTests/vmArithmeticTest/add4.json
  tests/laser/evm_testsuite/evm_test.py
Labels: Review

#468 Add support for loading bytecode from file
  mythril/interfaces/cli.py
Labels: to do

#450 Feature/432
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction/symbolic.py
Labels: Review

#452 Implement memory write function
  mythril/laser/ethereum/state.py
  tests/laser/state/mstate_test.py
Labels: in progress

#469 Initialize account with contract name
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction/symbolic.py
Labels: in progress

#472 Turn a print into a logger.warning and fix some small things...
  mythril/laser/ethereum/svm.py
Labels: Review

#476 Carry constraints with new transaction
  mythril/laser/ethereum/transaction/symbolic.py
Labels: Review

#475 Features/exp
  mythril/laser/ethereum/instructions.py
  tests/laser/evm_testsuite/evm_test.py
Labels: Review

#477 support sonar code coverage
  .circleci/config.yml
Labels: Review

#483 Use recursive transaction stack length passing
  mythril/laser/ethereum/taint_analysis.py
Labels: in progress

#492 Put issue instructions in comments...
  .github/ISSUE_TEMPLATE/analysis-module.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: in progress

#486 Use xml coverage report
  coverage_report.sh
Labels: Review
