Repository ConsenSys/mythril, pull requests merged in 2018-12, with the labels that each got.

#775 Calldata bugfixes
  mythril/laser/ethereum/state/calldata.py
Labels: Review

#773 Fix for --solv regression
  mythril/ethereum/util.py
  mythril/mythril.py
Labels: bug, in progress

#762 Initial StateAnnotation Implementation
  mythril/laser/ethereum/state/annotation.py
  mythril/laser/ethereum/state/global_state.py
  mythril/laser/ethereum/state/world_state.py
Labels: Review

#779 simplify boolref in sstore_()
  mythril/laser/ethereum/instructions.py
Labels: Review

#784 Minimize call value and transaction count
  mythril/analysis/solver.py
Labels: Review

#787 Enable creation bytecode option
  mythril/ethereum/evmcontract.py
  mythril/interfaces/cli.py
Labels: in progress

#792 Only execute callback modules when needed
  mythril/analysis/security.py
  mythril/analysis/symbolic.py
  mythril/mythril.py
Labels: Review

#797 deprecated_ops callback refactor
  mythril/analysis/modules/deprecated_ops.py
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.json
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.markdown
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.text
  tests/testdata/outputs_expected/origin.sol.o.json
  tests/testdata/outputs_expected/origin.sol.o.markdown
  tests/testdata/outputs_expected/origin.sol.o.text
Labels: Review

#807 Convert 1 arg to BitVecVal
  mythril/analysis/modules/external_calls.py
Labels: Review

#764 Memory refactor to store symbolic values (#685)
  .circleci/config.yml
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state/machine_state.py
  mythril/laser/ethereum/state/memory.py
  tests/laser/state/mstate_test.py
  tests/native_tests.sol
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.json
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.markdown
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.text
Labels: Review

#817 Fix py_ecc version
  requirements.txt
  setup.py
Labels: in progress

#819 Reverts minimizing transaction count
  mythril/analysis/solver.py
Labels: Review

#780 Switch to named loggers
  mythril/analysis/modules/base.py
  mythril/analysis/modules/delegatecall.py
  mythril/analysis/modules/dependence_on_predictable_vars.py
  mythril/analysis/modules/deprecated_ops.py
  mythril/analysis/modules/ether_thief.py
  mythril/analysis/modules/exceptions.py
  mythril/analysis/modules/external_calls.py
  mythril/analysis/modules/integer.py
  mythril/analysis/modules/suicide.py
  mythril/analysis/modules/transaction_order_dependence.py
  mythril/analysis/modules/unchecked_retval.py
  mythril/analysis/report.py
  mythril/analysis/security.py
  mythril/analysis/solver.py
  mythril/disassembler/disassembly.py
  mythril/ethereum/interface/leveldb/accountindexing.py
  mythril/ethereum/interface/leveldb/client.py
  mythril/ethereum/interface/rpc/client.py
  mythril/interfaces/cli.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/taint_analysis.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  mythril/laser/ethereum/util.py
  mythril/mythril.py
  mythril/support/loader.py
  mythril/support/signatures.py
  mythril/support/truffle.py
Labels: Review

#802 Exceptions module refactor
  mythril/analysis/modules/exceptions.py
Labels: Review

#803 Callback refactor for dependence on predictable vars
  mythril/analysis/call_helpers.py
  mythril/analysis/modules/dependence_on_predictable_vars.py
Labels: in progress

#822 queryable annotations
  mythril/laser/ethereum/state/global_state.py
  mythril/laser/ethereum/state/world_state.py
Labels: Review

#825 Callback refactor for delegatecall module
  mythril/analysis/modules/delegatecall.py
Labels: Review

#813 Extention of smt capabilities
  mythril/analysis/callgraph.py
  mythril/analysis/modules/ether_thief.py
  mythril/analysis/modules/external_calls.py
  mythril/analysis/modules/integer.py
  mythril/analysis/modules/suicide.py
  mythril/analysis/ops.py
  mythril/analysis/solver.py
  mythril/analysis/traceexplore.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/keccak.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/state/account.py
  mythril/laser/ethereum/state/calldata.py
  mythril/laser/ethereum/state/environment.py
  mythril/laser/ethereum/state/global_state.py
  mythril/laser/ethereum/state/memory.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/taint_analysis.py
  mythril/laser/ethereum/transaction/concolic.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  mythril/laser/ethereum/util.py
  mythril/laser/smt/__init__.py
  mythril/laser/smt/array.py
  mythril/laser/smt/bitvec.py
  mythril/laser/smt/bool.py
  mythril/laser/smt/expression.py
  mythril/laser/smt/solver.py
  tests/laser/evm_testsuite/evm_test.py
  tests/laser/state/calldata_test.py
  tests/laser/state/mstate_test.py
  tests/laser/state/storage_test.py
  tests/testdata/input_contracts/suicide.sol
Labels: Review

#833 use z3 simplify on variables extracted from z3.Model
  mythril/analysis/solver.py
Labels: in progress

#832 Some minor fixes
  mythril/analysis/modules/delegatecall.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/smt/__init__.py
Labels: Review

#828 Refactor multiple_sends.py
  mythril/analysis/modules/multiple_sends.py
Labels: in progress

#834 Refactor integer callback
  mythril/analysis/modules/integer.py
  mythril/laser/ethereum/instructions.py
  tests/graph_test.py
  tests/testdata/outputs_expected/overflow.sol.o.json
  tests/testdata/outputs_expected/overflow.sol.o.markdown
  tests/testdata/outputs_expected/overflow.sol.o.text
  tests/testdata/outputs_expected/underflow.sol.o.json
  tests/testdata/outputs_expected/underflow.sol.o.markdown
  tests/testdata/outputs_expected/underflow.sol.o.text
Labels: in progress

#840 Put BitVecVals into the storage
  mythril/laser/ethereum/state/account.py
Labels: Review

#835 Pop arguments for staticcall
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  tests/native_test.py
Labels: Review

#837 Unchecked retval
  mythril/analysis/modules/base.py
  mythril/analysis/modules/delegatecall.py
  mythril/analysis/modules/dependence_on_predictable_vars.py
  mythril/analysis/modules/deprecated_ops.py
  mythril/analysis/modules/ether_thief.py
  mythril/analysis/modules/exceptions.py
  mythril/analysis/modules/external_calls.py
  mythril/analysis/modules/integer.py
  mythril/analysis/modules/multiple_sends.py
  mythril/analysis/modules/suicide.py
  mythril/analysis/modules/transaction_order_dependence.py
  mythril/analysis/modules/unchecked_retval.py
  mythril/analysis/security.py
  mythril/analysis/symbolic.py
  tests/testdata/outputs_expected/calls.sol.o.json
  tests/testdata/outputs_expected/calls.sol.o.markdown
  tests/testdata/outputs_expected/calls.sol.o.text
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.json
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.markdown
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.text
  tests/testdata/outputs_expected/returnvalue.sol.o.json
  tests/testdata/outputs_expected/returnvalue.sol.o.markdown
  tests/testdata/outputs_expected/returnvalue.sol.o.text
Labels: Review

#831 Report issues when exception occurs
  mythril/analysis/security.py
  mythril/mythril.py
Labels: in progress

#851 Put BitVecVals in stack
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state/account.py
  mythril/laser/ethereum/state/memory.py
Labels: in progress

#854 Configure call to webhook in Circle CI build
  .circleci/config.yml
Labels: in progress

#856 Log number of open states at start of tx
  mythril/laser/ethereum/svm.py
Labels: Review
