Repository ConsenSys/mythril, pull requests merged in 2018-11, with the labels that each got.

#653 Hotfix/solc version binary
  mythril/ether/soliditycontract.py
  mythril/mythril.py
Labels: Review

#596 Fix #576: Add a new CLI option to load contract creation bytecode from the command line
  mythril/analysis/symbolic.py
  mythril/ether/ethcontract.py
  mythril/interfaces/cli.py
  mythril/laser/ethereum/svm.py
  mythril/mythril.py
  tests/cmd_line_test.py
Labels: in progress

#654 Related calldata and concretion improvements/fixes
  mythril/analysis/solver.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/transaction/transaction_models.py
  tests/laser/state/calldata_test.py
  tests/laser/transaction/symbolic_test.py
Labels: Review

#646 Add --no-onchain-storage-access flag
  mythril/interfaces/cli.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/util.py
  mythril/mythril.py
  mythril/support/loader.py
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/address0.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/address1.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy0.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy0_return.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy1.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy1_return.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy2.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy2_return.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopyUnderFlow.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopyZeroMemExpansion.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopyZeroMemExpansion_return.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh2.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh2_return.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh_return.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatacopy_sec.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldataload0.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldataload1.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldataload2.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldataloadSizeTooHigh.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldataloadSizeTooHighPartial.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldataload_BigOffset.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatasize0.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatasize1.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/calldatasize2.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/caller.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/callvalue.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/codecopy0.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/codecopyZeroMemExpansion.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/codecopy_DataIndexTooHigh.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/codesize.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/gasprice.json
  tests/laser/evm_testsuite/VMTests/vmEnvironmentalInfo/origin.json
  tests/laser/evm_testsuite/evm_test.py
Labels: Review

#666 Add multiple transactions to onchain analysis and fix suicide module
  mythril/analysis/modules/suicide.py
  mythril/laser/ethereum/svm.py
  mythril/support/truffle.py
  tests/cmd_line_test.py
  tests/native_test.py
  tests/report_test.py
  tests/svm_test.py
Labels: Review

#669 Mention specifc operator in arith overflow
  mythril/analysis/modules/integer.py
  signatures.json
  tests/testdata/outputs_expected/ether_send.sol.o.json
  tests/testdata/outputs_expected/ether_send.sol.o.markdown
  tests/testdata/outputs_expected/ether_send.sol.o.text
  tests/testdata/outputs_expected/overflow.sol.o.json
  tests/testdata/outputs_expected/overflow.sol.o.markdown
  tests/testdata/outputs_expected/overflow.sol.o.text
  tests/testdata/outputs_expected/underflow.sol.o.json
  tests/testdata/outputs_expected/underflow.sol.o.markdown
  tests/testdata/outputs_expected/underflow.sol.o.text
Labels: Review

#667 Solver per branch
  mythril/analysis/modules/dependence_on_predictable_vars.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
Labels: Review, high priority

#632 Feature/type hints develop
  mythril/interfaces/cli.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/cfg.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/keccak.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/strategy/basic.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/taint_analysis.py
  mythril/laser/ethereum/transaction/concolic.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  mythril/laser/ethereum/util.py
Labels: Review, enhancement

#678 Support Boolean constraints and support onchain analysis for ether_send
  mythril/analysis/analysis_utils.py
  mythril/analysis/modules/ether_send.py
  mythril/analysis/modules/suicide.py
  mythril/analysis/solver.py
Labels: Review

#686 Fix truffle source mappings and signatures
  mythril/support/truffle.py
Labels: Review

#687 Refactor logging and error messages (slightly)
  mythril/analysis/modules/external_calls.py
  mythril/analysis/solver.py
  mythril/ether/soliditycontract.py
  mythril/interfaces/cli.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/svm.py
  mythril/mythril.py
  mythril/support/loader.py
Labels: Review

#688 swc_id -> swc-id
  .github/ISSUE_TEMPLATE/analysis-module.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  mythril/analysis/report.py
  mythril/analysis/templates/report_as_markdown.jinja2
  mythril/analysis/templates/report_as_text.jinja2
  tests/report_test.py
  tests/testdata/outputs_expected/calls.sol.o.json
  tests/testdata/outputs_expected/environments.sol.o.json
  tests/testdata/outputs_expected/ether_send.sol.o.json
  tests/testdata/outputs_expected/exceptions.sol.o.json
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.json
  tests/testdata/outputs_expected/multi_contracts.sol.o.json
  tests/testdata/outputs_expected/origin.sol.o.json
  tests/testdata/outputs_expected/overflow.sol.o.json
  tests/testdata/outputs_expected/returnvalue.sol.o.json
  tests/testdata/outputs_expected/suicide.sol.o.graph.html
  tests/testdata/outputs_expected/suicide.sol.o.json
  tests/testdata/outputs_expected/underflow.sol.o.graph.html
  tests/testdata/outputs_expected/underflow.sol.o.json
Labels: in progress

#664 Add EnvironmentInfo tests
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/util.py
  tests/laser/evm_testsuite/evm_test.py
Labels: Review

#694 Correct the StackUnderflowException
  mythril/laser/ethereum/state.py
Labels: in progress

#695 Raise z3 version
  requirements.txt
  setup.py
Labels: Review

#696 Refactor Ether Send Module
  mythril/analysis/modules/ether_thief.py
  tests/cmd_line_test.py
  tests/testdata/outputs_expected/ether_send.sol.o.graph.html
  tests/testdata/outputs_expected/ether_send.sol.o.json
  tests/testdata/outputs_expected/ether_send.sol.o.markdown
  tests/testdata/outputs_expected/ether_send.sol.o.text
  tests/testdata/outputs_expected/multi_contracts.sol.o.graph.html
  tests/testdata/outputs_expected/multi_contracts.sol.o.json
  tests/testdata/outputs_expected/multi_contracts.sol.o.markdown
  tests/testdata/outputs_expected/multi_contracts.sol.o.text
Labels: Review, enhancement, security analysis

#700 Quick fix for z3 Pypi package versioning issue
  mythril/version.py
  requirements.txt
  setup.py
Labels: in progress

#698 Refactor state.py into multiple files
  mythril/analysis/analysis_utils.py
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/state/__init__.py
  mythril/laser/ethereum/state/account.py
  mythril/laser/ethereum/state/calldata.py
  mythril/laser/ethereum/state/constraints.py
  mythril/laser/ethereum/state/environment.py
  mythril/laser/ethereum/state/global_state.py
  mythril/laser/ethereum/state/machine_state.py
  mythril/laser/ethereum/state/world_state.py
  mythril/laser/ethereum/strategy/basic.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/taint_analysis.py
  mythril/laser/ethereum/transaction/concolic.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  tests/analysis/test_delegatecall.py
  tests/instructions/codecopy_test.py
  tests/laser/evm_testsuite/evm_test.py
  tests/laser/state/calldata_test.py
  tests/laser/state/mstack_test.py
  tests/laser/state/mstate_test.py
  tests/laser/state/storage_test.py
  tests/laser/test_transaction.py
  tests/laser/transaction/symbolic_test.py
  tests/native_test.py
  tests/svm_test.py
  tests/taint_result_test.py
  tests/taint_runner_test.py
Labels: Review

#702 Re application of #648
  mythril/analysis/modules/integer.py
Labels: Review

#708 Change gitter links and references to discord
  CONTRIBUTING.md
Labels: Priority: low, Review

#704 Deepcopy account state before deletion on selfdestuct
  mythril/laser/ethereum/instructions.py
Labels: Review

#712 Update version.py
  mythril/version.py
Labels: in progress

#709 Detection Module Refactoring
  mythril/analysis/modules/base.py
  mythril/analysis/modules/delegatecall.py
  mythril/analysis/modules/dependence_on_predictable_vars.py
  mythril/analysis/modules/deprecated_ops.py
  mythril/analysis/modules/ether_thief.py
  mythril/analysis/modules/exceptions.py
  mythril/analysis/modules/external_calls.py
  mythril/analysis/modules/integer.py
  mythril/analysis/modules/multiple_sends.py
  mythril/analysis/modules/suicide.py
  mythril/analysis/modules/transaction_order_dependence.py
  mythril/analysis/modules/unchecked_retval.py
  mythril/analysis/security.py
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/svm.py
  tests/analysis/test_delegatecall.py
  tests/native_test.py
  tests/svm_test.py
Labels: Priority: Critical, Review, security analysis

#713 Introduce additional constraints in Ether Thief module
  mythril/analysis/modules/ether_thief.py
Labels: Review

#718 Use unique name for balance variable
  mythril/laser/ethereum/state/account.py
Labels: in progress

#715 Baby steps to a better Ether Thief
  mythril/analysis/modules/ether_thief.py
  tests/testdata/outputs_expected/ether_send.sol.o.json
  tests/testdata/outputs_expected/ether_send.sol.o.markdown
  tests/testdata/outputs_expected/ether_send.sol.o.text
  tests/testdata/outputs_expected/multi_contracts.sol.o.json
  tests/testdata/outputs_expected/multi_contracts.sol.o.markdown
  tests/testdata/outputs_expected/multi_contracts.sol.o.text
Labels: Review

#716 Revert module loading behavour
  mythril/analysis/security.py
  mythril/interfaces/cli.py
Labels: Review

#719 Make transaction count fixed
  mythril/analysis/symbolic.py
  mythril/interfaces/cli.py
  mythril/laser/ethereum/svm.py
  mythril/mythril.py
  mythril/support/truffle.py
  tests/cmd_line_test.py
  tests/graph_test.py
  tests/native_test.py
  tests/report_test.py
  tests/svm_test.py
Labels: Review

#722 Quick fix for #721
  mythril/mythril.py
Labels: in progress

#727 Add missing constraint to get_transaction_sequence args
  mythril/analysis/modules/integer.py
Labels: in progress

#730 Refactor package and module structure
  mythril/analysis/symbolic.py
  mythril/disassembler/disassembly.py
  mythril/ether/__init__.py
  mythril/ether/evm.py
  mythril/ethereum/evmcontract.py
  mythril/ethereum/interface/leveldb/accountindexing.py
  mythril/ethereum/interface/leveldb/client.py
  mythril/ethereum/util.py
  mythril/mythril.py
  mythril/solidity/__init__.py
  mythril/solidity/soliditycontract.py
  mythril/support/truffle.py
  tests/disassembler_test.py
  tests/evmcontract_test.py
  tests/graph_test.py
  tests/laser/transaction/create_transaction_test.py
  tests/native_test.py
  tests/report_test.py
  tests/solidity_contract_test.py
  tests/svm_test.py
  tests/testdata/compile.py
Labels: Review

#735 Add better regex match for caller == address
  mythril/analysis/analysis_utils.py
Labels: Review

#753 Quick fix for tests
  mythril/ethereum/util.py
  mythril/mythril.py
  tests/cmd_line_test.py
  tests/laser/transaction/create_transaction_test.py
  tests/native_test.py
  tests/solidity_contract_test.py
  tests/svm_test.py
Labels: Review

#743 Bugfix: Some fixes around the callback refactor
  mythril/analysis/modules/suicide.py
  mythril/analysis/security.py
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/state/global_state.py
  tests/report_test.py
Labels: Review

#751 Make infura-mainnet the default option in CLI
  mythril/interfaces/cli.py
Labels: Review

#729 Trim 0x prefix on codecopy state transition (Issue #705)
  mythril/interfaces/cli.py
  mythril/laser/ethereum/instructions.py
Labels: Review

#754 Fix test contracts for solc 0.5.0
  mythril/ethereum/util.py
  mythril/mythril.py
  solidity_examples/BECToken.sol
  solidity_examples/WalletLibrary.sol
  solidity_examples/calls.sol
  solidity_examples/etherstore.sol
  solidity_examples/exceptions.sol
  solidity_examples/hashforether.sol
  solidity_examples/origin.sol
  solidity_examples/returnvalue.sol
  solidity_examples/rubixi.sol
  solidity_examples/suicide.sol
  solidity_examples/timelock.sol
  solidity_examples/token.sol
  solidity_examples/weak_random.sol
  tests/cmd_line_test.py
  tests/laser/transaction/create_transaction_test.py
  tests/native_test.py
  tests/native_tests.sol
  tests/solidity_contract_test.py
  tests/svm_test.py
  tests/testdata/input_contracts/calls.sol
  tests/testdata/input_contracts/constructor_assert.sol
  tests/testdata/input_contracts/environments.sol
  tests/testdata/input_contracts/ether_send.sol
  tests/testdata/input_contracts/exceptions.sol
  tests/testdata/input_contracts/kinds_of_calls.sol
  tests/testdata/input_contracts/metacoin.sol
  tests/testdata/input_contracts/multi_contracts.sol
  tests/testdata/input_contracts/nonascii.sol
  tests/testdata/input_contracts/origin.sol
  tests/testdata/input_contracts/overflow.sol
  tests/testdata/input_contracts/returnvalue.sol
  tests/testdata/input_contracts/rubixi.sol
  tests/testdata/input_contracts/suicide.sol
  tests/testdata/input_contracts/underflow.sol
  tests/testdata/input_contracts/weak_random.sol
Labels: Review, Testing, bug

#761 Refactor of calldata
  mythril/analysis/modules/integer.py
  mythril/analysis/solver.py
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/state/calldata.py
  mythril/laser/ethereum/state/environment.py
  mythril/laser/ethereum/transaction/concolic.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  tests/laser/state/calldata_test.py
  tests/testdata/input_contracts/overflow.sol
Labels: Review

#766 Remove the trailing "," in signaturesDB
  mythril/support/signatures.py
Labels: Review

#768 Update version.py
  mythril/version.py
Labels: in progress

#774 Create function for returndatacopy
  mythril/laser/ethereum/instructions.py
Labels: Review
