Repository ConsenSys/mythril, pull requests merged in 2018-07, with the labels that each got.

#304 Use bytecode length as CODESIZE
  mythril/disassembler/disassembly.py
  mythril/laser/ethereum/svm.py
Labels: Review

#307 Get contract code from infura for EXTCODESIZE
  mythril/laser/ethereum/svm.py
  mythril/mythril.py
Labels: Review

#311 bugfix: Add return statement to function
  mythril/laser/ethereum/call.py
Labels: Review

#312 Search strategy dfs
  mythril/laser/ethereum/strategy/__init__.py
  mythril/laser/ethereum/strategy/basic.py
  mythril/laser/ethereum/svm.py
Labels: Review

#313 Implement breadth first search
  mythril/laser/ethereum/strategy/basic.py
Labels: in progress

#317 fix ethereum to 2.3.1
  requirements.txt
  setup.py
Labels: in progress

#323 connect to infura with -l
  mythril/mythril.py
Labels: in progress

#316 Support 0x0 for extcodesize
  mythril/laser/ethereum/instructions.py
Labels: in progress

#308 Feature: online signature hash lookup and signatures refactor
  mythril/disassembler/disassembly.py
  mythril/mythril.py
  mythril/support/signatures.py
Labels: Review

#324 wip: Worklist fixes
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/instructions.py
Labels: Review

#332 Add timeout logging to solver
  mythril/analysis/solver.py
Labels: Review

#310 Modifies the symbolic suffixes enclosing them into brackets and sympl…
  mythril/laser/ethereum/instructions.py
Labels: Review

#334 Add contract to as dict
  mythril/analysis/report.py
  tests/testdata/outputs_expected/calls.sol.o.json
  tests/testdata/outputs_expected/ether_send.sol.o.json
  tests/testdata/outputs_expected/exceptions.sol.o.json
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.json
  tests/testdata/outputs_expected/metacoin.sol.o.json
  tests/testdata/outputs_expected/multi_contracts.sol.o.json
  tests/testdata/outputs_expected/origin.sol.o.json
  tests/testdata/outputs_expected/overflow.sol.o.json
  tests/testdata/outputs_expected/returnvalue.sol.o.json
  tests/testdata/outputs_expected/suicide.sol.o.json
  tests/testdata/outputs_expected/underflow.sol.o.json
Labels: in progress

#331 Implement coverage measurement
  mythril/laser/ethereum/svm.py
Labels: in progress

#336 Rlp
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/util.py
  requirements.txt
  setup.py
Labels: in progress

#338 Include fallback function
  mythril/laser/ethereum/svm.py
Labels: Review

#328 Hook implementation
  mythril/laser/ethereum/call.py
  mythril/laser/ethereum/svm.py
Labels: in progress

#339 check for z3 before simplify
  mythril/laser/ethereum/instructions.py
Labels: in progress

#326 Bugfix/320
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/natives.py
  mythril/laser/ethereum/util.py
Labels: Review

#343 Set initial function name to fallback
  mythril/laser/ethereum/svm.py
Labels: Review

#335 Search strategy selection and timeout implementation
  mythril/analysis/symbolic.py
  mythril/interfaces/cli.py
  mythril/laser/ethereum/svm.py
  mythril/mythril.py
  mythril/support/truffle.py
  tests/graph_test.py
  tests/report_test.py
  tests/svm_test.py
Labels: in progress

#342 Refactor search
  mythril/interfaces/cli.py
  mythril/leveldb/client.py
  mythril/mythril.py
  setup.py
Labels: Review

#347 Check for length bin runtime
  mythril/ether/soliditycontract.py
Labels: in progress

#333 Load all contracts from file
  mythril/ether/soliditycontract.py
  mythril/mythril.py
Labels: Review

#345 Bugfix 314
  mythril/laser/ethereum/instructions.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/taint_analysis.py
Labels: Review, in progress

#358 Speed up search & some cleanup
  mythril/disassembler/disassembly.py
  mythril/ether/ethcontract.py
  mythril/leveldb/client.py
Labels: Review

#361 mythril/analysis/modules/ether_send.py
  mythril/analysis/modules/ether_send.py
Labels: in progress

#359 Add -V and --version myth CLI option
  mythril/interfaces/cli.py
  mythril/version.py
  setup.py
Labels: in progress

#366 Feature/contract hash to address mapping
  mythril/interfaces/cli.py
  mythril/leveldb/accountindexing.py
  mythril/leveldb/client.py
  mythril/leveldb/eth_db.py
  mythril/mythril.py
  requirements.txt
  setup.py
Labels: in progress

#372 Leveldb code cleanup
  mythril/leveldb/accountindexing.py
  mythril/leveldb/client.py
  mythril/leveldb/eth_db.py
Labels: in progress

#374 Python 3.5 tolerance and note what Python versions Mythril accepts
  all_tests.sh
  myth
  mythril/__init__.py
  mythril/mythril.py
  setup.py
  tox.ini
Labels: in progress

#355 Implements initial transaction based symbolic execution
  mythril/laser/ethereum/cfg.py
  mythril/laser/ethereum/state.py
  mythril/laser/ethereum/svm.py
  mythril/laser/ethereum/transaction.py
  tests/native_test.py
  tests/svm_test.py
Labels: Review

#357 Enhance/340
  mythril/ether/soliditycontract.py
  mythril/interfaces/cli.py
  mythril/mythril.py
Labels: Review

#380 Use solidity filename for truffle
  mythril/support/truffle.py
Labels: Review

#381 Use bytes encoding to make the mapping
  mythril/ether/soliditycontract.py
  mythril/support/truffle.py
Labels: Review

#383 Send a list for functions
  mythril/mythril.py
  mythril/support/signatures.py
Labels: in progress

#368 Revise issue templates
  .github/ISSUE_TEMPLATE/analysis-module.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Review

#385 Force determinism in iterating over dictionary keys...
  mythril/ether/soliditycontract.py
Labels: in progress

#378 Fix function signature search
  mythril/ether/ethcontract.py
  mythril/leveldb/client.py
Labels: Review
