Repository ConsenSys/mythril, pull requests merged in 2019-04, with the labels that each got.

#983 Use plugin loader and factory
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/plugins/plugin_factory.py
  mythril/laser/ethereum/plugins/plugin_loader.py
  requirements.txt
  setup.py
Labels: in progress

#986 Use instruction coverage plugin
  mythril/analysis/symbolic.py
  mythril/laser/ethereum/plugins/implementations/benchmark.py
  mythril/laser/ethereum/plugins/implementations/coverage.py
  mythril/laser/ethereum/svm.py
Labels: Review

#989 Coverage based search strategy
  mythril/laser/ethereum/plugins/implementations/coverage/__init__.py
  mythril/laser/ethereum/plugins/implementations/coverage/coverage_plugin.py
  mythril/laser/ethereum/plugins/implementations/coverage/coverage_strategy.py
  mythril/laser/ethereum/strategy/__init__.py
Labels: Review

#994 Propose some changes to enhance/886
  mythril/analysis/modules/external_calls.py
  mythril/analysis/modules/state_change_external_calls.py
Labels: in progress

#971 Fix the jsonv2 output for the type of the contract
  mythril/analysis/report.py
  mythril/ethereum/evmcontract.py
  mythril/mythril.py
  mythril/mythril/mythril_analyzer.py
  mythril/support/source_support.py
  mythril/support/support_utils.py
  tests/report_test.py
  tests/testdata/outputs_expected/ether_send.sol.o.jsonv2
  tests/testdata/outputs_expected/metacoin.sol.o.jsonv2
  tests/testdata/outputs_expected/nonascii.sol.o.jsonv2
Labels: Review

#997 Add creation hash to the code
  mythril/support/source_support.py
Labels: in progress

#1000 Fix jsonv2 log format
  mythril/analysis/report.py
  mythril/interfaces/cli.py
Labels: Priority: High, bug, in progress

#1002 Add the runtime bytecode to source list
  mythril/analysis/symbolic.py
  mythril/disassembler/disassembly.py
  mythril/laser/ethereum/state/account.py
  mythril/laser/ethereum/state/world_state.py
  mythril/laser/ethereum/transaction/symbolic.py
  mythril/laser/ethereum/transaction/transaction_models.py
  mythril/support/source_support.py
Labels: Review

#919 Detect State changes after external calls
  mythril/analysis/call_helpers.py
  mythril/analysis/modules/external_calls.py
  mythril/analysis/modules/state_change_external_calls.py
  mythril/laser/ethereum/call.py
  tests/testdata/outputs_expected/calls.sol.o.json
  tests/testdata/outputs_expected/calls.sol.o.jsonv2
  tests/testdata/outputs_expected/calls.sol.o.markdown
  tests/testdata/outputs_expected/calls.sol.o.text
  tests/testdata/outputs_expected/kinds_of_calls.sol.o.jsonv2
Labels: Review

#998 Add the fix for transaction count
  mythril/interfaces/cli.py
Labels: in progress

#1006 Add create2 opcode to hooks state change after call
  mythril/analysis/modules/state_change_external_calls.py
Labels: in progress
